---
title: "Statistical Computing"
author: "Shantanu Madaboosi"
output: 
  ioslides_presentation:
    css: styles.css
    smaller: yes
    widescreen: yes
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(shiny)
library(ggplot2)
library(shinyWidgets)
library(shinyAce)
library(shinyjs)
```


***********************************
##### Metropolish-Hastings Random Walk
Poisson random variable with parameter $\lambda$.
```{r}

target <- function(x,l){
  if(x<0){
    return(0)
  }else{
    return(((l**x)*exp(-l))/factorial(x))
  }
}

mcmc <- function(n,l){
  curr <- 0
  for(i in 1:n){
    proposal <- curr + sample(c(-1,1),1)
    accept <- target(proposal,l)/target(curr,l)
    if(runif(1) < accept){
      curr <- proposal
    }
  }
  curr
}

funcmcmc <- aceEditor("mcmc",
                      value = paste('target <- ',paste(format(target), 
                                                       collapse = '\n'),
                                    '\n\nmcmc <- ',
                                    paste(format(mcmc),
                                          collapse = '\n')),
                      mode = 'r',
                      theme = 'dawn',
                      readOnly = TRUE,
                      height = '220px')
```

```{r}
# Input UI
ui <- fluidPage(
  fluidRow(
    column(6,
           funcmcmc
    ),
    column(6,
           textOutput('param'),
           verbatimTextOutput("avgroll"),
           tags$head(
             tags$style(
               "#avgroll{ font-size:12px; overflow-y:scroll; max-height: 220px}")
           )
    )
  ),
  fluidRow(
    column(4,
           wellPanel(
             fluidRow(
               column(6,
                      numericInput("nroll", label = "n", 
                                   min = 1,
                                   value = 100)
               ),
               column(6,
                      numericInput("nrep", label = "Replications",
                                   min = 1,
                                   value = 1000)
               )
             ),
             
             numericInput("l", label = "Lambda",
                          min = 1,
                          value = 5),
             fluidRow(
               column(6,             
                      actionButton('simulate',label = 'Run')
               ),
               column(6,
                      verbatimTextOutput('mu')
               )
             )
           )
    ),
    mainPanel(
      plotOutput('dist',
                 height = 280)
    )
  )
)

# Define server logic 
server <- function(input, output) {
  rundat <- eventReactive(input$simulate,{
    out <- replicate(input$nrep,mcmc(input$nroll,input$l))
    data.frame('simlist' = out)
  })
  output$mu <- renderPrint({
    mean(rundat()$simlist)
  })
  # output$param <- renderText({
  #   'Output:'
  # })
  output$avgroll <- renderPrint({
    "SIMLIST"
    rundat()$simlist
  }) 
  output$dist <- renderPlot({
    # data <- density(rundat())
    # plot(data, main="Random Walk Density")
    # polygon(data, col="steelblue4", border="steelblue1")
    ggplot(rundat(), aes(x = simlist)) + 
      geom_density(fill = 'steelblue4',
                   adjust=2,
                   alpha = .5)
  })
}
shinyApp(ui = ui, server = server)
```



***********************************
##### Monte-Carlo Inegration

$$\int_{0}^{4} \sin(x^{x})dx$$
```{r}
mcf <- function(x){
  return(sin(x**x))
}

funcmcf <- aceEditor("mcf",
                     value = paste('mcf <- ',
                                   paste(format(mcf),
                                         collapse = '\n'),
                                   'integrate(mcf,0,4)'),
                     mode = 'r',
                     theme = 'dawn',
                     readOnly = TRUE,
                     height = '100px')
```

```{r}
MCint <- function(){
  n <- 10000
  simlist <- mcf(runif(n, 0, 4))
  list('mu' = mean(simlist)*4, 'simlist' = simlist)
}
funcmc <- aceEditor("MCint",
                    value = paste('MCint <- ',
                                  paste(format(MCint),
                                        collapse = '\n')),
                    mode = 'r',
                    theme = 'dawn',
                    readOnly = TRUE,
                    height = '150px')

```

```{r}
ui <- fluidPage(useShinyjs(),
                fluidRow(
                  column(6,
                         funcmcf
                  ),
                  column(6,
                         verbatimTextOutput('out')
                  )
                ),
                fluidRow(
                  column(6,
                         funcmc,
                         actionButton('run', label = 'Run')
                  ),
                  column(6,
                         verbatimTextOutput('out2'),
                         tags$head(
                           tags$style(
                             "#out2{ font-size:12px; overflow-y: scroll; max-height: 100px}")
                         ),
                         verbatimTextOutput('samp'),
                         tags$head(
                           tags$style(
                             "#samp{ font-size:12px; overflow-y: scroll; max-height: 250px}")
                         )
                  )
                )
                
)
server <- function(input, output) {
  mcintrun2 <- eventReactive(input$run,{
    data <- MCint()
    data
  })
  mcintrun <- eventReactive(input$run,{
    integrate(mcf,0,4)
  })
  output$out <- renderPrint({
    mcintrun()
  })
  output$out2 <- renderPrint({
    out <- mcintrun2()$mu
    out
  })
  output$samp <- renderPrint({
    data <- data.frame("simlist" = mcintrun2()$simlist)
    data
  })
}
shinyApp(ui = ui ,server = server)
```


***********************************
##### Pythagrian Theorom Calculator  

```{r}
hypotenuse <- function(a,b){
  sqrt((a**2) + (b**2))
}
funchypo <- aceEditor("hypotenuse",
                      value = paste(format(hypotenuse), collapse = '\n'),
                      mode = 'r',
                      theme = 'dawn',
                      readOnly = TRUE,
                      height = '90px')
```

```{r}
# Input UI
ui <- fluidPage(
  mainPanel(
    plotOutput("triangle",
               height = 500,
               width = 800)),
  column(4,
         fluidRow(
           funchypo
         ),
         fluidRow(
           wellPanel(
             numericInput("a",
                          label = "Length 'a'", 
                          min = 1,
                          value = 10,
                          width = 150
             ),
             numericInput("b", 
                          label = "Length 'b'",
                          min = 1,
                          value = 10,
                          width = 150
             )
           )
         )
  )
)


# Define server logic 
server <- function(input, output) {
  output$triangle <- renderPlot({
    hyp <- hypotenuse(input$a,input$b)
    ggplot() + 
      geom_line(
        aes(x = c(0,0),
            y = c(0,input$a))) + 
      geom_line(
        aes(x = c(0,input$b),
            y = c(input$a,0))) + 
      geom_line(
        aes(x = c(input$b,0),
            y = c(0,0)))+ 
      ylim(0,
           max(c(input$a,input$b))) + 
      xlim(0,
           max(c(input$a,input$b))) + 
      geom_label(
        aes(x=(0.5*(input$b)),
            y=0, 
            label=paste('b =',input$b)),
        size = 5) +
      geom_label(
        aes(x= 0,
            y=(0.5*(input$a)),
            label=paste('a =',input$a)),
        size = 5) +
      geom_label(
        aes(x = (input$b/2),
            y = (input$a/2), 
            label=paste('c =',round(hyp,3))),
        size = 5,
        col = 'blue') +
      theme(
        panel.background = element_rect(fill = "gray100"),
        # plot.background = element_blank(),
        panel.grid.major = element_line(color = "gray85"),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank()
      )
  })
}
shinyApp(ui = ui, server = server)
``` 



***********************************
##### Tetrahedron Dice Simulation

```{r}
diceRoll <- function(nroll,nrep){
  simlist1 <- numeric(nrep)
  for(i in 1:length(simlist1)){
    simlist2 <- numeric(nroll)
    for(j in 1:length(simlist2)){
      trial <- sample(1:4,1,replace = TRUE)
      simlist2[j] <- trial
    }
    simlist1[i] <- mean(simlist2)
  }
  list("mu" = mean(simlist1),"data" = simlist1)
}

funcdice <- aceEditor("diceRoll",
                      value = paste(format(diceRoll), collapse = '\n'),
                      mode = 'r',
                      theme = 'dawn',
                      readOnly = TRUE,
                      height = '230px')
```

```{r} 
# Input UI
ui <- fluidPage(useShinyjs(),
                fluidRow(
                  column(7,
                         funcdice),
                  column(5,
                         wellPanel(
                           numericInput("nroll", label = "Rolls per trial", 
                                        min = 1,
                                        value = 10),
                           
                           numericInput("nrep", label = "Trials",
                                        min = 1,
                                        value = 1000),
                           actionButton('simulate',label = 'Simulate & Average')
                         ),
                         verbatimTextOutput("avgroll"),
                         tags$head(
                           tags$style(
                             "#avgroll{ font-size:12px; overflow-y: scroll; max-height: 100px}")
                         )
                  )
                ),
                fluidRow(
                  plotOutput('dist',
                             height = 240)
                )
)

# Define server logic 
server <- function(input, output) {
  
  roll <- eventReactive(input$simulate,{
    data <- diceRoll(input$nroll,input$nrep)
    data
  })
  output$dist <- renderPlot({
    data <- data.frame('rolls' = roll()$data)
    mu <- data.frame('mu' = roll()$mu)
    ggplot(data, aes(x = rolls))+
      geom_density(fill = 'steelblue4', alpha = .5, adjust = 2) + 
      geom_label(aes(x = mu$mu, y = 0.5, label = paste0('mean = ',mu$mu)))
  })
}
shinyApp(ui = ui, server = server)
```


***********************************
##### MCMC cryptography algorithm
```{r}

message <- "coincidences in general are great stumbling blocks in the way of that class of thinkers who have been educated to know nothing of the theory of probabilities that theory to which the most glorious objects of human research are indebted for the most glorious of illustrations edgar allen poe the murders in the rue morgue morpheus this is your last chance after this there is no turning back you take the blue pill the story ends you wake up in your bed and believe whatever you want to believe you take the red pill you stay in wonderland and i show you how deep the rabbit hole goes"

set.seed(1)

#  mat <- read.table("ShakeCount.txt",header=F)
mat <- read.table("AustenCount.txt",header=F)
logmat <- log(mat + 1)

# Computes the score of the decoded message using the given code
score <- function(code)
{  
  p <- 0
  # For each pair of letters in the decoded message
  # query the transition matrix for the probability of that pair
  for (i in 1:(nchar(message)-1)){
    p <- p + logmat[charIndex(substr(code, i, i)),charIndex(substr(code, i+1, i+1))]
  }
  # return the sum of these probabilities
  p
}

# ascii(char) returns the numerical ascii value for char
ascii <- function(char)
{ 
  strtoi(charToRaw(char),16L) #get 'raw' ascii value
} 

# charIndex takes in a character and returns its 'char value'
# defined as a=1, b=2, ..., z=26, space=27
# this matches the array created by read.table
charIndex <- function(char)
{
  aValue <- ascii(char)
  if (aValue == 32)
  {
    # return 27 if a space
    27
  } else
  {
    #ascii sets "a" as 97, so subtract 96
    aValue - 96 
  }
}

# Decrypts code according to curFunc	
decrypt <- function(code,curFunc)
{  	
  out <- code
  # for each character in the message, decode it according to the curFunc
  for (i in 1:nchar(message))
  {
    charInd <- charIndex(substr(code,i,i))
    if (charInd < 27)
    {
      # change the ith character to the character determined by the curFunc
      substr(out,i,i) <- rawToChar(as.raw(curFunc[charInd] + 96))
    }
  }
  out 
}

# codemess holds the scrambled message
codemess <- decrypt(message,sample(1:26))

# instantiate a map to hold previously computed codes' scores
map <- new.env(hash=T, parent=emptyenv())

# we begin with a basic (a->a, z->z) function for decrypting the codemess
curFunc <- 1:27
# calculate the score for curFunc and store it in the map
oldScore <- score(decrypt(codemess,curFunc))
map[[paste(curFunc, collapse='')]] <- oldScore
```

```{r}
decode <- function(codemess,map,currFunc,
                   oldScore, message){
  for (iteration in 1:7000) {
    # sample two letters to swap
    swaps <- sample(1:26,2)
    oldFunc <- curFunc
    
    ### <b>
    oldScore <- score(decrypt(codemess,oldFunc))
    ### </b>
    
    # let curFunc be oldFunc 
    # but with two letters swapped
    curFunc[swaps[1]] <- oldFunc[swaps[2]]
    curFunc[swaps[2]] <- oldFunc[swaps[1]]
    
    # if we have already scored this decoding,
    # retrieve score from our map
    if (exists(paste(curFunc, collapse =''), map)){
      newScore <- map[[paste(curFunc, collapse ='')]]
    } else
      # if we have not already scored this decoding,
      # calculate it and store it in the map
    {
      newScore <- score (decrypt(codemess,curFunc))
      map[[paste(curFunc, collapse = '')]] <- newScore
    }
    accept <- exp(newScore-oldScore)
    # decide whether to accept curFunc
    # or to revert to oldFunc
    if (runif(1) > accept)
    {
      curFunc <- oldFunc
    } else 
    {
      incProgress(1/1600)
      oldScore <- newScore
    }
    
    # print out our decryption every 100 iterations
    # if ((iteration %%  1000) == 0)
    # {
    #   print(c(iteration,decrypt(codemess,curFunc)))
    # }
    if(decrypt(codemess,curFunc) == message){
      print(decrypt(codemess,curFunc))
      print(iteration)
      incProgress(1)
      break
    }
  }
}
funcdecode <- aceEditor("decode",
                        value = paste(format(decode), collapse = '\n'),
                        mode = 'r',
                        theme = 'dawn',
                        readOnly = TRUE,
                        height = '500px')
```

```{r} 
# Input UI
ui <- fluidPage(useShinyjs(),
                column(7,
                       funcdecode
                ),
                column(5,
                       wellPanel(
                         textOutput('codemess'),
                         tags$head(
                           tags$style(type="text/css",
                                      "#codemess{ font-size:12px; overflow-y: scroll; max-height: 220px}")),
                         actionButton('run',label = 'Decrypt')
                       )
                ),
                column(5,
                       verbatimTextOutput("code"),
                       tags$head(
                         tags$style(
                           "#code{ font-size:12px;overflow-y: scroll; max-height: 220px}")
                       ),
                       verbatimTextOutput('outmsg',placeholder = TRUE),
                       tags$head(
                         tags$style(
                           "#outmsg{ font-size:12px; overflow-y: scroll; max-height: 220px}")
                       )
                )
                
                
)

# Define server logic 
server <- function(input, output) {
  
  output$codemess <- renderText({
    codemess
  })
  

  ## Show output from sample Run
  output$outmsg <- renderText({
    paste("[1] coincidences in general are great stumbling blocks in the way of that class of thinkers who have been educated to know nothing of the theory of probabilities that theory to which the most glorious objects of human research are indebted for the most glorious of illustrations edgar allen poe the murders in the rue morgue morpheus this is your last chance after this there is no turning back you take the blue pill the story ends you wake up in your bed and believe whatever you want to believe you take the red pill you stay in wonderland and i show you how deep the rabbit hole goes\n\n[1] 1434", collapse = '\n')
  })
  observeEvent(input$run,{
    hide('outmsg')
    hide("run")
  })
  out <- eventReactive(input$run,{
    # progress$set(message = "Computing data", value = 0)
    # Close the progress when this reactive exits (even if there's an error)
    withProgress(message = 'Decrypting... This may take a while', value = 0, {
        Sys.sleep(0.25)
        decode(codemess, map,currFunc,oldScore,message)
    }
        )
  })
  output$code <- renderPrint({
    out()
    show("run")
  })
}
shinyApp(ui = ui, server = server)
```









